services:
  - type: web
    name: instagram-video-scraper
    env: node
    buildCommand: |
      npm install
      apt-get update && apt-get install -y chromium
    startCommand: npm start
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium